---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: instance
    image: arm64v8/python:3.9-slim
    privileged: true
    pre_build_image: true

provisioner:
  name: ansible

verifier:
  name: testinfra

